server:
  port: 8101
  servlet:
    session:
      timeout: 30
  tomcat:
    url-encoding: UTF-8
myenvironment:
  name: 开发环境
spring:
  datasource:
    #localhost
    #121.5.199.228
    #127.0.0.1
    #  zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true  Asia/Shanghai   GMT%2B8 ->这个代表东八区
    url: jdbc:mysql://121.5.199.228/SelectSystem?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8

    username: root
    password: 123456
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: hwxadmin
        login-password: hwx001125
      web-stat-filter:
        enabled: true
        urlpattern: /*
        exclusions: '*.js,*.jgp,*.png,*.gif,*.css,*.ico,/druid/*'
      filter:
        slow-sql-millis: 1000
        logslowsql: true
        enabled: true
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  mapper-locations: classpath:Mybatis/*.xml

